In [2]:
import pandas as pd

# Series

Creazione di una serie in Pandas:

In [3]:
s = pd.Series([5,6,12,1.3], index = ['A','B','C','D'], name = 'serie_0')
print(s)

A     5.0
B     6.0
C    12.0
D     1.3
Name: serie_0, dtype: float64

Accesso ad una series:

In [4]:
print(s[:2])

A    5.0
B    6.0
Name: serie_0, dtype: float64

# Dataframe

Creazione di un dataframe:

In [5]:
ds=pd.DataFrame({'foo':[0., 4., 8., -12.,16],
                 'bar':['x', 'y', 'z', 'w','a']
                 },
                index=['A','B','C','D','E'])
print(ds)

    foo bar
A   0.0   x
B   4.0   y
C   8.0   z
D -12.0   w
E  16.0   a


Hands-on excercise (slide 29)

Can you guess what if the output of
* pd.DataFrame({'foo':[1,2,6],'fee':[3,4,5]})
* pd.DataFrame({'foo':{'a':1,'b':1},'fee':{'c':1,'d':2}}

In [15]:
## complete
1    3 
2    4
6    5
#e
1.0  NaN
1.0  NaN
NaN  1.0
NaN  2.0

SyntaxError: invalid syntax (238173989.py, line 2)

Importazione di un CSV in un dataframe e stampa dei primi 5 record:

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/Apress/data-analysis-and-visualization-using-python/master/Ch07/Salaries.csv")
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

## Hands on SALARIES
Accesso agli attributi di un dataframe (esercizio slide 35):

In [7]:
print('Number of records:')
print(df.shape)
print('Number of total cells:')
print(df.size)
print('Column names:')
print(df.columns)
print('Column types:')
print(df.dtypes)

Number of records:
(78, 6)
Number of total cells:
468
Column names:
Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='str')
Column types:
rank            str
discipline      str
phd           int64
service       int64
sex             str
salary        int64
dtype: object

In [8]:
print(f'The represented disciplines are')

The represented disciplines are

In [9]:
print('How many unique discipline values appear in the dataframe?\n')
print(df['discipline'].nunique())

How many unique discipline values appear in the dataframe?

2

In [10]:
print('How many records are associated with unique discipline values?\n')
print(df.groupby('discipline').size())

How many records are associated with unique discipline values?

discipline
A    36
B    42
dtype: int64

## Hands on SALARIES

Accesso ai metodi di un dataframe (esercizio slide 37):

In [11]:
numeric_columns=['phd','service','salary']
print('Summary of numeric columns:')
print(df[numeric_columns].describe())
print('Standard deviations of numeric colums:')
print(df[numeric_columns].std())
print('Mean values of the first 50 records:')
print(df[numeric_columns].head(50).mean())

Summary of numeric columns:
             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000
Standard deviations of numeric colums:
phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64
Mean values of the first 50 records:
phd            21.52
service        17.60
salary     113789.14
dtype: float64

Lista di tutti i metodi

In [12]:
dir(df)[226:]

['asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'discipline',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'phd',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'service',
 'set_axis',
 'set_flags',
 'set_index',
 'sex',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

### comprehensive summary of df infos

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     str
 1   discipline  78 non-null     str
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     str
 5   salary      78 non-null     int64
dtypes: int64(3), str(3)
memory usage: 3.8 KB

In [ ]:
print("count how many nan values appear in each column of the df")
df.isna().sum()

count how many nan values appear in each column of the df

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [ ]:
print("sample 3 elements from a df\n")
print(df.sample(3))

print("\nsample a fraction of elements in the df\n")
df.sample(frac=0.1)

sample 3 elements from a df

        rank discipline  phd  service     sex  salary
7       Prof          A   18       18    Male  126300
50  AsstProf          B   10        5  Female   97032
60  AsstProf          B    3        3  Female   92000

sample a fraction of elements in the df

         rank discipline  phd  service     sex  salary
67       Prof          A   17       11  Female   90450
61  AssocProf          B   13       10  Female  103750
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
54  AssocProf          A   25       22  Female   62884
12   AsstProf          B    1        0    Male   88000
11       Prof          B   23       23    Male  134778
65       Prof          A   36       19  Female  117555

# Processing tables using pandas

## Selection/Slicing:

In [ ]:
print('select only rows with salaries larger than 120000 euros\n\n')
df_sub=df[df['salary']>120000]
print(df_sub)

select only rows with salaries larger than 120000 euros


    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

HANDS ON: Slicing/filtering (esercizio slide 41:)

* Calculate the basic statistics for the salary column;
* Find how many values in the salary column (use count_values method);
* Calculate the average salary
* Select the female professors with a salary greater than 120000
* Select the salary column of female professors

In [ ]:
print('Basic statistics of the salary column')
print(df['salary'].describe())
print('\n\nThe number of records in the salary column is ')
print(df['salary'].count)
print('\n\nThe average salary is ')
print(df['salary'].mean())
print('\n\nRecords related to female professor with a salary larger than 120k')
print(df[(df['salary']>120000) & (df['sex']=='female')])
print('\n\nSalary column of female professors')
print(df[(df['salary']) & (df['sex'] == 'female')])

Basic statistics of the salary column
count        78.000000
mean     108023.782051
std       28293.661022
min       57800.000000
25%       88612.500000
50%      104671.000000
75%      126774.750000
max      186960.000000
Name: salary, dtype: float64


The number of records in the salary column is
<bound method Series.count of 0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64>


The average salary is
108023.78205128205


Records related to female professor with a salary larger than 120k
Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []


Salary column of female professors
Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

## iloc and loc methods

In [ ]:
print('Slicing a dataframe using loc')
df.loc[30:40,['rank','service','salary']]

Slicing a dataframe using loc

         rank  service  salary
30  AssocProf        7  107008
31       Prof       21  155750
32       Prof       19  103275
33       Prof       18  120000
34  AssocProf        8  119800
35       Prof       23  126933
36       Prof       45  146856
37       Prof        8  102000
38   AsstProf        3   91000
39       Prof       18  129000
40       Prof       36  137000

In [ ]:
print('Let us apply loc to a sub dataframe')
df_sub=df[df['salary']>120000]
print(df_sub.head(20))

print('\n\n\nNote that loc slicing refers to index values! It is not linked to row positions in the dataframe! ')
print(df_sub.loc[10:20,['rank','salary']]) ##note that the first entry in the loc method refers to the index values

Let us apply loc to a sub dataframe
    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096



Note that loc slicing refers to index values! It is not linked to row positions in the dataframe!
    rank  salary
10  Prof  128250
11  Prof  134778
13  Prof  162200
14  Prof  153750
15  Prof  150480
19  Prof  150500

In [ ]:
print('Let us now apply iloc slicing to the dataframe')
print(df.iloc[:3,[0,1,2 ]])

print('\nAs in the df the index values are increasing and continuous integer number, \nthe result is equivalent to what we would obtain using the loc method')

Let us now apply iloc slicing to the dataframe
   rank discipline  phd
0  Prof          B   56
1  Prof          A   12
2  Prof          A   23

As in the df the index values are increasing and continuous integer number,
the result is equivalent to what we would obtain using the loc method

In [ ]:
print('Let us now apply iloc on subdf')

print(df_sub.iloc[10:30,[0,1,2]])

print('\nnote that the first entry in the iloc method refers to the record position, not to the index!')

Let us now apply iloc on subdf
    rank discipline  phd
26  Prof          A   38
27  Prof          A   45
29  Prof          B   21
31  Prof          B   22
35  Prof          B   28
36  Prof          B   45
39  Prof          B   18
40  Prof          A   39
44  Prof          B   23
45  Prof          B   25
49  Prof          B   17
51  Prof          B   20
58  Prof          B   36
72  Prof          B   24
75  Prof          B   17

note that the first entry in the iloc method refers to the record position, not to the index!

## Aggregate:

In [ ]:
numeric_columns=['phd','service','salary']

print('print sum of colum values per row\n')
print(df[numeric_columns].sum(axis=1, skipna=True),'\n')
print('print the average column values\n')
print(df[numeric_columns].mean(),'\n')
print('Print the standard deviation of the salary column values\n')
df_s=df[['salary']]
print(df_s.std())
print('Print the standardized salary using zscore formula (value-mean)/std:\n')
ts_stand=(df_s-df_s.mean())/df_s.std()
print(ts_stand)
print('Add the standardized salary to df:\n')
df['std-salary']=ts_stand
df.head()

print sum of colum values per row

0     187065
1      93018
2     110558
3     131276
4     104838
       ...
73    105478
74    104567
75    124346
76    109996
77    109684
Length: 78, dtype: int64

print the average column values

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

Print the standard deviation of the salary column values

salary    28293.661022
dtype: float64
Print the standardized salary using zscore formula (value-mean)/std:

      salary
0   2.789891
1  -0.530995
2   0.088049
3   0.819308
4  -0.113940
..       ...
73 -0.090967
74 -0.123059
75  0.575684
76  0.068221
77  0.057335

[78 rows x 1 columns]
Add the standardized salary to df:

   rank discipline  phd  service   sex  salary  std-salary
0  Prof          B   56       49  Male  186960    2.789891
1  Prof          A   12        6  Male   93000   -0.530995
2  Prof          A   23       20  Male  110515    0.088049
3  Prof          A   40       31  Male  131205    0.819308
4  Prof          B   20       18  Male  104800   -0.113940

In [ ]:
print('Print some selected statistics (sum,min,prod) on the salary column')

df['salary'].agg(['sum','min','prod'])

Print some selected statistics (sum,min,prod) on the salary column

sum     8425855
min       57800
prod          0
Name: salary, dtype: int64

## Map:

In [ ]:
print('The sex column entries exhibit capital letters.')
print(df['sex'].head())
print('Format the column so that no capital letter appears.')
df['sex']=df['sex'].str.lower()
print(df['sex'].head())

The sex column entries exhibit capital letters.
0    Male
1    Male
2    Male
3    Male
4    Male
Name: sex, dtype: object
Format the column so that no capital letter appears.
0    male
1    male
2    male
3    male
4    male
Name: sex, dtype: object

In [ ]:
def dollarConvert(x):
  return x*1.07

print('define a function converting salary values form euros to dollars')
df['dollar']=df['salary'].map(dollarConvert)
df

define a function converting salary values form euros to dollars

         rank discipline  phd  service     sex  salary  std-salary     dollar
0        Prof          B   56       49    male  186960    2.789891  200047.20
1        Prof          A   12        6    male   93000   -0.530995   99510.00
2        Prof          A   23       20    male  110515    0.088049  118251.05
3        Prof          A   40       31    male  131205    0.819308  140389.35
4        Prof          B   20       18    male  104800   -0.113940  112136.00
..        ...        ...  ...      ...     ...     ...         ...        ...
73       Prof          B   18       10  female  105450   -0.090967  112831.50
74  AssocProf          B   19        6  female  104542   -0.123059  111859.94
75       Prof          B   17       17  female  124312    0.575684  133013.84
76       Prof          A   28       14  female  109954    0.068221  117650.78
77       Prof          A   23       15  female  109646    0.057335  117321.22

[78 rows x 8 columns]

## Group-by:

In [ ]:
print('let us now group df records by rank')
df_rank=df.groupby(['rank'])
print('The groups obtained correspond to unique rank values\n')
print(df_rank.groups)
print('\nAfter grouping we can compute aggregate measures on each group. \nLet us compute the mean values on numerical column.\n')
numeric_cols=df.columns[df.dtypes.isin(['int64','float64'])]
print(df_rank[numeric_cols].mean())

let us now group df records by rank
The groups obtained correspond to unique rank values

{'AssocProf': [6, 30, 34, 41, 47, 54, 56, 59, 61, 62, 64, 71, 74], 'AsstProf': [12, 16, 17, 20, 22, 23, 28, 38, 42, 43, 46, 50, 53, 55, 57, 60, 66, 68, 70], 'Prof': [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 14, 15, 18, 19, 21, 24, 25, 26, 27, 29, 31, 32, 33, 35, 36, 37, 39, 40, 44, 45, 48, 49, 51, 52, 58, 63, 65, 67, 69, 72, 73, 75, 76, 77]}

After grouping we can compute aggregate measures on each group.
Let us compute the mean values on numerical column.

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

## Concat:

In [ ]:
print('Let us now introduce df1, a new dataframe with few records')
df1=pd.DataFrame({'rank':['AssocProf','Prof','AsstProf'],'salary':[91786.23,123624.80,81362.78]})
print(df1)


print('\n\nUse default concatenation of df and df1:')
df_u=pd.concat([df,df1])
print(df_u)
print('Mind that indices keep their original values! It would be better to reinitialize the index.')
print(df_u.reset_index(drop=True))


print('\n\nWhat happens if we concatenate columns and use inner join?')
df_j=pd.concat([df,df1],axis=1,join='inner')
print(df_j)
print('It searches for records having the same index values and concatenates them.\n Columns with the same name but different entries are duplicated.')

Let us now introduce df1, a new dataframe with few records
        rank     salary
0  AssocProf   91786.23
1       Prof  123624.80
2   AsstProf   81362.78


Use default concatenation of df and df1:
         rank discipline   phd  service     sex     salary
0        Prof          B  56.0     49.0    Male  186960.00
1        Prof          A  12.0      6.0    Male   93000.00
2        Prof          A  23.0     20.0    Male  110515.00
3        Prof          A  40.0     31.0    Male  131205.00
4        Prof          B  20.0     18.0    Male  104800.00
..        ...        ...   ...      ...     ...        ...
76       Prof          A  28.0     14.0  Female  109954.00
77       Prof          A  23.0     15.0  Female  109646.00
0   AssocProf        NaN   NaN      NaN     NaN   91786.23
1        Prof        NaN   NaN      NaN     NaN  123624.80
2    AsstProf        NaN   NaN      NaN     NaN   81362.78

[81 rows x 6 columns]
Mind that indices keep their original values! It would be better to reinitialize the index.
         rank discipline   phd  service     sex     salary
0        Prof          B  56.0     49.0    Male  186960.00
1        Prof          A  12.0      6.0    Male   93000.00
2        Prof          A  23.0     20.0    Male  110515.00
3        Prof          A  40.0     31.0    Male  131205.00
4        Prof          B  20.0     18.0    Male  104800.00
..        ...        ...   ...      ...     ...        ...
76       Prof          A  28.0     14.0  Female  109954.00
77       Prof          A  23.0     15.0  Female  109646.00
78  AssocProf        NaN   NaN      NaN     NaN   91786.23
79       Prof        NaN   NaN      NaN     NaN  123624.80
80   AsstProf        NaN   NaN      NaN     NaN   81362.78

[81 rows x 6 columns]


What happens if we concatenate columns and use inner join?
   rank discipline  phd  service   sex  salary       rank     salary
0  Prof          B   56       49  Male  186960  AssocProf   91786.23
1  Prof          A   12        6  Male   93000       Prof  123624.80
2  Prof          A   23       20  Male  110515   AsstProf   81362.78
It searches for records having the same index values and concatenates them.
 Columns with the same name but different entries are duplicated.

## Merge:

In [ ]:
df2=pd.DataFrame({'discipline':['A','B'], 'description':['computer science','math']})
df_d=pd.merge(df,df2)
df_d

         rank discipline  phd  service     sex  salary       description
0        Prof          B   56       49    Male  186960              math
1        Prof          A   12        6    Male   93000  computer science
2        Prof          A   23       20    Male  110515  computer science
3        Prof          A   40       31    Male  131205  computer science
4        Prof          B   20       18    Male  104800              math
..        ...        ...  ...      ...     ...     ...               ...
73       Prof          B   18       10  Female  105450              math
74  AssocProf          B   19        6  Female  104542              math
75       Prof          B   17       17  Female  124312              math
76       Prof          A   28       14  Female  109954  computer science
77       Prof          A   23       15  Female  109646  computer science

[78 rows x 7 columns]

### Sorting:

In [ ]:
print("Sort values by service")
df_sorted=df.sort_values(by=['service'])
print(df_sorted.head())

print("Sort values by discipline and service")
df_double_sorted=df.sort_values(by=['discipline','service'])
print(df_double_sorted.head())

Sort values by service
        rank discipline  phd  service     sex  salary
55  AsstProf          A    2        0  Female   72500
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000
Sort values by discipline and service
        rank discipline  phd  service     sex  salary
23  AsstProf          A    2        0    Male   85000
52      Prof          A   12        0  Female  105000
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
22  AsstProf          A    4        2    Male   73000

### Hands on SALARIES (slide 53)

*  Given the dataset df_2 defined below, merge df and df_2 keeping record union (outer).

*  How many nans in the dataset?

*  Drop rows containing nan values

*  Sort values according to discipline and Dept

*  Compute the average distribution of Females anf Males in the three Departments.

In [ ]:
import numpy as np
import random
r=random.randint(20,70)
dept=np.random.choice(['Math','CS','Phys'],r)
df_2=df[['rank','phd','salary']].sample(r).copy()
df_2['Dept']=dept
df_2

         rank  phd  salary  Dept
53   AsstProf    5   73500  Phys
75       Prof   17  124312  Phys
20   AsstProf    4   92000  Phys
2        Prof   23  110515  Math
29       Prof   21  123683  Phys
46   AsstProf   11   74692    CS
4        Prof   20  104800    CS
11       Prof   23  134778    CS
19       Prof   29  150500    CS
70   AsstProf    8   78500  Math
66   AsstProf    7   63100  Math
57   AsstProf    3   72500    CS
35       Prof   28  126933    CS
73       Prof   18  105450  Phys
63       Prof   29   91000  Math
44       Prof   23  151768  Math
33       Prof   18  120000  Phys
0        Prof   56  186960  Phys
65       Prof   36  117555    CS
58       Prof   36  144651  Math
76       Prof   28  109954  Math
52       Prof   12  105000  Math
37       Prof   20  102000  Math
21       Prof   33  103106  Math
23   AsstProf    2   85000    CS
40       Prof   39  137000  Phys
24       Prof   30   91100  Math
12   AsstProf    1   88000  Math
34  AssocProf   12  119800  Phys
56  AssocProf   10   77500  Math
51       Prof   20  127512    CS
67       Prof   17   90450  Phys
42   AsstProf    4   80225    CS
50   AsstProf   10   97032  Phys
74  AssocProf   19  104542    CS
32       Prof   27  103275  Phys
27       Prof   45  155865  Phys
71  AssocProf   12   71065  Phys
72       Prof   24  161101  Phys
47  AssocProf   11  103613  Math
36       Prof   45  146856    CS
25       Prof   35   99418  Phys
48       Prof   17  111512  Phys
77       Prof   23  109646    CS
43   AsstProf    5   77000    CS
5        Prof   20  122400    CS
59  AssocProf   12  103994  Phys
30  AssocProf    9  107008  Phys
49       Prof   17  122960  Phys
68   AsstProf    4   77500  Math
55   AsstProf    2   72500  Math
9        Prof   51   57800    CS
64  AssocProf   26   73300    CS
14       Prof   25  153750  Math
41  AssocProf   13   74830  Phys

In [ ]:
print('merged dataset using outher method')
df_merged=pd.merge(df,df_2,on='rank',how='outer')
print(df_merged)
print('Count the number of nans per column')
print(df.isna().sum())
print('Drop rows containing nan values')
df.isna().dropna(inplace=True)
print('sort values by discipline and Dept values')
df_sorted = df_merged.sort_values(by=['discipline', 'Dept'], ascending=True)
print(df_sorted)
print('Compute the number of males and females per department')
df_grouped=df_merged.groupby(['Dept','sex'])

merged dataset using outher method
           rank discipline  phd_x  service     sex  salary_x  phd_y  salary_y  \
0     AssocProf          A     20       17    Male     81285     12    119800
1     AssocProf          A     20       17    Male     81285     10     77500
2     AssocProf          A     20       17    Male     81285     19    104542
3     AssocProf          A     20       17    Male     81285     12     71065
4     AssocProf          A     20       17    Male     81285     11    103613
...         ...        ...    ...      ...     ...       ...    ...       ...
1877       Prof          A     23       15  Female    109646     23    109646
1878       Prof          A     23       15  Female    109646     20    122400
1879       Prof          A     23       15  Female    109646     17    122960
1880       Prof          A     23       15  Female    109646     51     57800
1881       Prof          A     23       15  Female    109646     25    153750

      Dept
0     Phys
1     Math
2       CS
3     Phys
4     Math
...    ...
1877    CS
1878    CS
1879  Phys
1880    CS
1881  Math

[1882 rows x 9 columns]
Count the number of nans per column
rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64
Drop rows containing nan values
sort values by discipline and Dept values
           rank discipline  phd_x  service     sex  salary_x  phd_y  salary_y  \
2     AssocProf          A     20       17    Male     81285     19    104542
7     AssocProf          A     20       17    Male     81285     26     73300
29    AssocProf          A     13        8  Female     74830     19    104542
34    AssocProf          A     13        8  Female     74830     26     73300
47    AssocProf          A     25       22  Female     62884     19    104542
...         ...        ...    ...      ...     ...       ...    ...       ...
1806       Prof          B     17       17  Female    124312     45    155865
1807       Prof          B     17       17  Female    124312     24    161101
1809       Prof          B     17       17  Female    124312     35     99418
1810       Prof          B     17       17  Female    124312     17    111512
1813       Prof          B     17       17  Female    124312     17    122960

      Dept
2       CS
7       CS
29      CS
34      CS
47      CS
...    ...
1806  Phys
1807  Phys
1809  Phys
1810  Phys
1813  Phys

[1882 rows x 9 columns]
Compute the number of males and females per department

# Other meaningful examples of map method

In [ ]:
print('How can we map a colum containing lists of fixed lenght into multiple columns?')

data = pd.DataFrame({'Patient':['A','B','C'],
    'measurements': [
        [10, 20, 30, 40, 50],
        [15, 25, 35, 45, 55],
        [12, 22, 32, 42, 52]
    ]
})
print('\nOriginal Data')
print(data)

def map_list(lst):
    return pd.Series(lst)


new_columns=data['measurements'].apply(map_list)
new_columns.columns=[f'measure_{i}' for i in range(1,new_columns.shape[1]+1)]
print('\nNew Columns')
print(new_columns)


data=pd.concat([data[['Patient']],new_columns],axis=1)
print('\nNew Data')
print(data)

How can we map a colum containing lists of fixed lenght into multiple columns?

Original Data
  Patient          measurements
0       A  [10, 20, 30, 40, 50]
1       B  [15, 25, 35, 45, 55]
2       C  [12, 22, 32, 42, 52]

New Columns
   measure_1  measure_2  measure_3  measure_4  measure_5
0         10         20         30         40         50
1         15         25         35         45         55
2         12         22         32         42         52

New Data
  Patient  measure_1  measure_2  measure_3  measure_4  measure_5
0       A         10         20         30         40         50
1       B         15         25         35         45         55
2       C         12         22         32         42         52

In [ ]:
# Example DataFrame with a column containing lists of various lengths
data = pd.DataFrame({'Patient':['A','B','C','D','E'],
    'measurements': [
        [10, 20, 30, 40, 50],
        [15, 25],
        [12, 22, 32],
        [8],
        []
    ]
})


new_columns=data['measurements'].apply(map_list)
new_columns.columns=[f'measure_{i}' for i in range(1,new_columns.shape[1]+1)]
print('\nNew Columns')
print(new_columns)


data=pd.concat([data[['Patient']],new_columns],axis=1)
print('\nNew Data')
print(data)

New Columns
   measure_1  measure_2  measure_3  measure_4  measure_5
0       10.0       20.0       30.0       40.0       50.0
1       15.0       25.0        NaN        NaN        NaN
2       12.0       22.0       32.0        NaN        NaN
3        8.0        NaN        NaN        NaN        NaN
4        NaN        NaN        NaN        NaN        NaN

New Data
  Patient  measure_1  measure_2  measure_3  measure_4  measure_5
0       A       10.0       20.0       30.0       40.0       50.0
1       B       15.0       25.0        NaN        NaN        NaN
2       C       12.0       22.0       32.0        NaN        NaN
3       D        8.0        NaN        NaN        NaN        NaN
4       E        NaN        NaN        NaN        NaN        NaN

# Data from Kaggle

Mount google drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

Use Kaggle username and key

In [ ]:
import os
os.environ['KAGGLE_USERNAME'] = 'nnnnnnnnnnn'
os.environ['KAGGLE_KEY'] = 'kkkkkkkkk'

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [ ]:
##CHANGE PATH ACCORDING THE NOTEBOOK LOCATION
os.chdir('/content/drive/MyDrive/your_notebook_folder_path') ##!!change path

In [ ]:
!kaggle datasets download -d fedesoriano/body-fat-prediction-dataset
##CHANGE PATH ACCORDING THE NOTEBOOK LOCATION
!unzip /content/drive/MyDrive/your_notebook_folder_path/body-fat-prediction-dataset.zip ##!!change path

body-fat-prediction-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  /content/drive/MyDrive/Colab_Notebooks/BDA/body-fat-prediction-dataset.zip
replace bodyfat.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/your_notebook_folder_path/bodyfat.csv') ##!!change path
df.head(20)

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
5,1.0502,20.9,24,210.25,74.75,39.0,104.5,94.4,107.8,66.0,42.0,25.6,35.7,30.6,18.8
6,1.0549,19.2,26,181.00,69.75,36.4,105.1,90.7,100.3,58.4,38.3,22.9,31.9,27.8,17.7
7,1.0704,12.4,25,176.00,72.50,37.8,99.6,88.5,97.1,60.0,39.4,23.2,30.5,29.0,18.8
8,1.0900,4.1,25,191.00,74.00,38.1,100.9,82.5,99.9,62.9,38.3,23.8,35.9,31.1,18.2
9,1.0722,11.7,23,198.25,73.50,42.1,99.6,88.6,104.1,63.1,41.7,25.0,35.6,30.0,19.2
10,1.0830,7.1,26,186.25,74.50,38.5,101.5,83.6,98.2,59.7,39.7,25.2,32.8,29.4,18.5
11,1.0812,7.8,27,216.00,76.00,39.4,103.6,90.9,107.7,66.2,39.2,25.9,37.2,30.2,19.0
12,1.0513,20.8,32,180.50,69.50,38.4,102.0,91.6,103.9,63.4,38.3,21.5,32.5,28.6,17.7
13,1.0505,21.2,30,205.25,71.25,39.4,104.1,101.8,108.6,66.0,41.5,23.7,36.9,31.6,18.8
14,1.0484,22.1,35,187.75,69.50,40.5,101.3,96.4,100.1,69.0,39.0,23.1,36.1,30.5,18.2
15,1.0512,20.9,35,162.75,66.00,36.4,99.1,92.8,99.2,63.1,38.7,21.7,31.1,26.4,16.9
16,1.0333,29.0,34,195.75,71.00,38.9,101.9,96.4,105.2,64.8,40.8,23.1,36.2,30.8,17.3
17,1.0468,22.9,32,209.25,71.00,42.1,107.6,97.5,107.0,66.9,40.0,24.4,38.2,31.6,19.3
18,1.0622,16.0,28,183.75,67.75,38.0,106.8,89.6,102.4,64.2,38.7,22.9,37.2,30.5,18.5
19,1.0610,16.5,33,211.75,73.50,40.0,106.2,100.5,109.0,65.8,40.6,24.0,37.1,30.1,18.2

The variables listed below, from left to right, are:

*   Density determined from underwater weighing
*   Percent body fat from Siri's (1956) equation
*   Age (years)
*   Weight (lbs)
*   Height (inches)
*   Neck circumference (cm)
*   Chest circumference (cm)
*   Abdomen 2 circumference (cm)
*   Hip circumference (cm)
*   Thigh circumference (cm)
*   Knee circumference (cm)
*   Ankle circumference (cm)
*   Biceps (extended) circumference (cm)
*   Forearm circumference (cm)
*   Wrist circumference (cm)

## Exercise

### 1) Print dataset basic properties
- Number of cells, rows, columns

### 2) Check data types

### 3) Compute summary statistics
- Is there something unusual? (Check, e.g., the Height column)
- Is that a real value or an error? (Filter patients to check)

### 4) Compute the average Density
- For patients with BodyFat > 0.25
- For patients with BodyFat < 0.2
- Is this an intuitive result?

### 5) Add a BMI column
BMI formula: $BMI = \frac{\text{Weight (kg)}}{\text{Height (m)}^2}$

- Add a column containing Weight in kg:  $ 1 \text{ lb} = 0.453 \text{ kg}$
- Add a column containing Height in meters: $ 1 \text{ inch} = 0.0254 \text{ m} $
- Add the BMI column to the df

### 6) Define categorical BMI classes
```python
 df['cBMI'] = pd.cut(df['BMI'], bins=[0,20,27,100], labels=['underweight','normal','overweight'])
```
- Group by `cBMI` and compute average statistics

#### COMPLETE THE EXERCISE

## PART 2 - Tidy Data dataset

#### HANDS-ON:

In [ ]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/nickhould/tidy-data-python/master/data/pew-raw.csv")
print('import data from "https://raw.githubusercontent.com/nickhould/tidy-data-python/master/data/pew-raw.csv"\n')
print(df.head(50))
print('check the content of the file\n')
print("Melt the data to get a tidy df\n")
print(df.columns)
pd.melt(df,id_vars='religion',value_vars=['<$10k', '$10-20k','$20-30k','$30-40k', '$40-50k','$50-75k'], var_name='Income', value_name='Frequency')

import data from "https://raw.githubusercontent.com/nickhould/tidy-data-python/master/data/pew-raw.csv"

                   religion   <$10k   $10-20k  $20-30k  $30-40k   $40-50k  \
0                  Agnostic      27        34       60       81        76
1                   Atheist      12        27       37       52        35
2                  Buddhist      27        21       30       34        33
3                  Catholic     418       617      732      670       638
4         Dont know/refused      15        14       15       11        10
5         Evangelical Prot      575       869     1064      982       881
6                    Hindu        1         9        7        9        11
7  Historically Black Prot      228       244      236      238       197
8         Jehovahs Witness       20        27       24       24        21
9                   Jewish       19        19       25       25        30

   $50-75k
0      137
1       70
2       58
3     1116
4       35
5     1486
6       34
7      223
8       30
9       95
check the content of the file

Melt the data to get a tidy df

Index(['religion', ' <$10k', ' $10-20k', '$20-30k', '$30-40k', ' $40-50k',
       '$50-75k'],
      dtype='str')

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['<$10k', '$10-20k', '$40-50k']"

### Tidy Data 2: product sales data

Download the dataset and import it in your drive folder https://www.kaggle.com/datasets/ksabishek/product-sales-data

Inspect dataframe content and validate data types. Are they consistent? (spoiler alert, they are not). Use pd.to_datetime(df['Date'],dayfirst=True)to validate datetime data.

Melt the data so to reach a tidy dataset

In [ ]:
# download sales data
!kaggle datasets download -d ksabishek/product-sales-data

!unzip /content/drive/BigData/Prima_Esercitazione/product-sales-data.zip ## change path

zsh:1: command not found: kaggle
unzip:  cannot find or open /content/drive/BigData/Prima_Esercitazione/product-sales-data.zip, /content/drive/BigData/Prima_Esercitazione/product-sales-data.zip.zip or /content/drive/BigData/Prima_Esercitazione/product-sales-data.zip.ZIP.

In [ ]:
# import and inspect content
# validate data types. Hint: pd.to_datetime(df['Date'],dayfirst=True)

In [ ]:
#melt the data to get a tidy dataset

In [ ]:
pd.options.mode.copy_on_write = True
df_sales=pd.read_csv('/content/drive/MyDrive/path/statsfinal.csv',index_col=0) ##change path
df_sales.head()

#### Using pd.wide_to_long

In [ ]:
import numpy as np

df = pd.DataFrame(
    {
        "A1970": {0: "a", 1: "b", 2: "c"},
        "A1980": {0: "d", 1: "e", 2: "f"},
        "B1970": {0: 2.5, 1: 1.2, 2: 0.7},
        "B1980": {0: 3.2, 1: 1.3, 2: 0.1},
        "X": dict(zip(range(3), np.random.randn(3))),
        "id": dict(zip(range(3), range(3))),
    }
)

print('Original dataset')
print(df)

wtl=pd.wide_to_long(df, stubnames=["A", "B"], i="id", j="year")
print('wide-to-long transformation')
print(wtl)

Original dataset
  A1970 A1980  B1970  B1980         X  id
0     a     d    2.5    3.2 -0.816032   0
1     b     e    1.2    1.3  0.043604   1
2     c     f    0.7    0.1 -1.522316   2
wide-to-long transformation
                X  A    B
id year
0  1970 -0.816032  a  2.5
1  1970  0.043604  b  1.2
2  1970 -1.522316  c  0.7
0  1980 -0.816032  d  3.2
1  1980  0.043604  e  1.3
2  1980 -1.522316  f  0.1

### Exercise:
Use the dataset from the previous exercise and make it tidy using the wide-to-long method

In [ ]:
## complete

### Stack and Unstack

In [ ]:
df_single_level_cols = pd.DataFrame([[0, 1], [2, 3]],
                                     index=['cat', 'dog'],
                                     columns=['weight', 'height'])

# Displaying original data
print("Original Data:")
print(df_single_level_cols)

print("\nStacked Data:")
stacked_data=df_single_level_cols.stack()
print(stacked_data)

print("\nUnstacked Back:")
unstacked_data=stacked_data.unstack(level=1)
print(unstacked_data)


print("\nif unstacking with wrong level:")
w_unstacked_data=stacked_data.unstack(level=0)
print(w_unstacked_data)

Original Data:
     weight  height
cat       0       1
dog       2       3

Stacked Data:
cat  weight    0
     height    1
dog  weight    2
     height    3
dtype: int64

Unstacked Back:
     weight  height
cat       0       1
dog       2       3

if unstacking with wrong level:
        cat  dog
weight    0    2
height    1    3

In [ ]:
##### HANDS-ON

import pandas as pd

##to set a column as the index use df.set_index('columns_to_become_index', inplace=True)

# Creating a DataFrame with sales data
data = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West'],
    'Product_A': [100, 150, 200, 250],
    'Product_B': [120, 160, 220, 280],
    'Product_C': [130, 170, 240, 300]
})

#Use stack and unstack it to get the results in slide 23

#### Further examples using map, stack and explode

In [ ]:
### Take the example from the map method cells
### maybe multiple rows would be better than multiple columns in this case
def map_list(lst):
    return pd.Series(lst)

# Example DataFrame with a column containing lists of various lengths
data = pd.DataFrame({'Patient':['A','B','C','D','E'],
    'measurements': [
        [10, 20, 30, 40, 50],
        [15, 25],
        [12, 22, 32],
        [8],
        []
    ]
})
print('Original data')
print(data)

new_columns=data['measurements'].apply(map_list)
print('\nNew Columns')
print(new_columns)


new_data=pd.concat([data[['Patient']],new_columns],axis=1)
print('\nNew Data')
print(new_data)

##make this dataset long using stack
new_data.set_index('Patient',inplace=True)
stacked_data=new_data.stack().reset_index()
print('\nNew stacked Data')
print(stacked_data)

# Much easier with df.explode that explodes the 'measurements' column into multiple rows
exploded_data = data.explode('measurements')

print('\nExploded Data')
print(exploded_data)

Original data
  Patient          measurements
0       A  [10, 20, 30, 40, 50]
1       B              [15, 25]
2       C          [12, 22, 32]
3       D                   [8]
4       E                    []

New Columns
      0     1     2     3     4
0  10.0  20.0  30.0  40.0  50.0
1  15.0  25.0   NaN   NaN   NaN
2  12.0  22.0  32.0   NaN   NaN
3   8.0   NaN   NaN   NaN   NaN
4   NaN   NaN   NaN   NaN   NaN

New Data
  Patient     0     1     2     3     4
0       A  10.0  20.0  30.0  40.0  50.0
1       B  15.0  25.0   NaN   NaN   NaN
2       C  12.0  22.0  32.0   NaN   NaN
3       D   8.0   NaN   NaN   NaN   NaN
4       E   NaN   NaN   NaN   NaN   NaN

New stacked Data
   Patient  level_1     0
0        A        0  10.0
1        A        1  20.0
2        A        2  30.0
3        A        3  40.0
4        A        4  50.0
5        B        0  15.0
6        B        1  25.0
7        C        0  12.0
8        C        1  22.0
9        C        2  32.0
10       D        0   8.0

Exploded Data
  Patient measurements
0       A           10
0       A           20
0       A           30
0       A           40
0       A           50
1       B           15
1       B           25
2       C           12
2       C           22
2       C           32
3       D            8
4       E          NaN

## Pivoting

In [ ]:
import numpy as np
data = {
    "value": np.random.randn(20),
    "variable": ["A"] * 10 + ["B"] * 10,
    "category": np.random.choice(["type1", "type2", "type3", "type4"], 20),
    "date": (
        list(pd.date_range("1/1/2000", periods=10, freq="M"))
        + list(pd.date_range("1/1/2000", periods=10, freq="M"))
    ),
}
df = pd.DataFrame(data, columns=["date", "variable", "category", "value"])
df.sort_values(by=['date'],inplace=True)


print('\nOriginal data')
print(df)

pivoted_df=df.pivot(index="date", columns="variable", values="value")
print('\nPivoted on single column')
print(pivoted_df)


pivoted2_df=df.pivot(index="date", columns=["category","variable"], values="value")
print('\nPivoted on two colums')
print(pivoted2_df)

Original data
         date variable category     value
0  2000-01-31        A    type4 -0.587419
10 2000-01-31        B    type3  2.430159
1  2000-02-29        A    type1  0.467901
11 2000-02-29        B    type2 -2.470781
2  2000-03-31        A    type3  0.298999
12 2000-03-31        B    type3 -0.255454
3  2000-04-30        A    type2 -0.145388
13 2000-04-30        B    type1 -1.113720
4  2000-05-31        A    type3  1.333355
14 2000-05-31        B    type3 -1.226735
5  2000-06-30        A    type3  0.070296
15 2000-06-30        B    type3 -2.022547
6  2000-07-31        A    type4  1.801242
16 2000-07-31        B    type2  1.774179
17 2000-08-31        B    type3  0.725221
7  2000-08-31        A    type2 -0.510035
18 2000-09-30        B    type1 -0.187762
8  2000-09-30        A    type4 -2.707613
9  2000-10-31        A    type1 -0.869790
19 2000-10-31        B    type1 -0.474619

Pivoted on single column
variable           A         B
date
2000-01-31 -0.587419  2.430159
2000-02-29  0.467901 -2.470781
2000-03-31  0.298999 -0.255454
2000-04-30 -0.145388 -1.113720
2000-05-31  1.333355 -1.226735
2000-06-30  0.070296 -2.022547
2000-07-31  1.801242  1.774179
2000-08-31 -0.510035  0.725221
2000-09-30 -2.707613 -0.187762
2000-10-31 -0.869790 -0.474619

Pivoted on two colums
category       type4     type3     type1     type2     type3     type2  \
variable           A         B         A         B         A         A
date
2000-01-31 -0.587419  2.430159       NaN       NaN       NaN       NaN
2000-02-29       NaN       NaN  0.467901 -2.470781       NaN       NaN
2000-03-31       NaN -0.255454       NaN       NaN  0.298999       NaN
2000-04-30       NaN       NaN       NaN       NaN       NaN -0.145388
2000-05-31       NaN -1.226735       NaN       NaN  1.333355       NaN
2000-06-30       NaN -2.022547       NaN       NaN  0.070296       NaN
2000-07-31  1.801242       NaN       NaN  1.774179       NaN       NaN
2000-08-31       NaN  0.725221       NaN       NaN       NaN -0.510035
2000-09-30 -2.707613       NaN       NaN       NaN       NaN       NaN
2000-10-31       NaN       NaN -0.869790       NaN       NaN       NaN

category       type1
variable           B
date
2000-01-31       NaN
2000-02-29       NaN
2000-03-31       NaN
2000-04-30 -1.113720
2000-05-31       NaN
2000-06-30       NaN
2000-07-31       NaN
2000-08-31       NaN
2000-09-30 -0.187762
2000-10-31 -0.474619

### Exercise:

In [ ]:
# HANDS ON:
# Consider a previous excercise few cells above:
# Creating a DataFrame with sales data
data = pd.DataFrame({
    'Region': ['North', 'South', 'East', 'West'],
    'Product_A': [100, 150, 200, 250],
    'Product_B': [120, 160, 220, 280],
    'Product_C': [130, 170, 240, 300]
})

# Set 'Region' column as index
data.set_index('Region', inplace=True)

# Displaying original data
print("Original Data:")
print(data)

#Use pivoting to get the the results shown in slide 27

Original Data:
        Product_A  Product_B  Product_C
Region
North         100        120        130
South         150        160        170
East          200        220        240
West          250        280        300

Stacked Data:
   Region    Product    0
0   North  Product_A  100
1   North  Product_B  120
2   North  Product_C  130
3   South  Product_A  150
4   South  Product_B  160
5   South  Product_C  170
6    East  Product_A  200
7    East  Product_B  220
8    East  Product_C  240
9    West  Product_A  250
10   West  Product_B  280
11   West  Product_C  300

Wide Format Data:
Product  Product_A  Product_B  Product_C
Region
East           200        220        240
North          100        120        130
South          150        160        170
West           250        280        300